apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 9085
  - name: redis
    image: redis
    ports:
    - containerPort: 9033
